displayName=BA Gamble Tracker
author=vividflash
description=Record Low/Medium BA Gamble Rewards to Loot Tracker.
tags=barbarian,assault,ba,gamble,minigame,loot,tracker
plugins=com.vividflash.bagambletracker.BaGambleTrackerPlugin
build=standard
version=1.0
