displayName=BA Gamble Tracker
author=vividflash
description=Records the rewards from Barbarian Assault low and medium gambles in the Loot Tracker.
tags=barbarian,assault,ba,gamble,minigame,loot,tracker
plugins=com.vividflash.bagambletracker.BaGambleTrackerPlugin
build=standard
version=1.0
